### ISSUE TITLE
It seems that some files are missing

### ISSUE THREAD

**Issue by leyiweb** [deeplearning-wisc/dice#1]
Hello, I am very interested in your work, and I am very happy to see the open source work, but I found that the get_Mahalanobis_score method under score.py does not seem to be provided, and the code of the ImageNet experiment is missing, is it convenient to provide it later?

**Comment by sunyiyou** [comment]
Hi, the demo code for ImageNet experiment is updated. get_Mahalanobis_score is not used in this demo, so you can ignore it.
