### ISSUE TITLE
would you be willing to provide the code on how the weights in the checkpoints folder were trained?

### ISSUE THREAD

**Issue by ColdAsYou165** [deeplearning-wisc/dice#6]
I trained two models, DenseNet and ResNet18, using the CIFAR-10 dataset, and achieved an accuracy of 0.94. Then, I attempted to reproduce the results of using the DICE method for out-of-distribution (OOD) detection. However, I found that only the results of the DenseNet model matched my expectations, whereas the ResNet18 model showed an increase in false positive rate (FPR) when using the DICE method.
Could you please share the code for training the models? It would be even better if you could provide the code specifically for training ResNet18 on CIFAR-10.

**Comment by sunyiyou** [comment]
Hi, 
In the paper, we use DenseNet-101 for the CIFAR experiment. 
However, we do have code for training ResNet18 at https://github.com/sunyiyou/train_module.

**Comment by ColdAsYou165** [comment]
Many thanks!
